DevPackage/force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Ferrari</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Lamborghini</fullName>
            </value>
            <value>
                <fullName>Mustang</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevPackage/force-app/main/default/objects/Product2/fields/Has_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Has_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Promotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DataFactory.cls
@isTest public with sharing class DataFactory {
    public static List<Product2> getAllCars(Integer counter){
        List<Product2> listOfProducts = new List<Product2>();
        for (Integer i = 0; i < counter; i++) {
            Product2 prod = new Product2();
            prod.Name = 'FT-1';
            prod.Brand__c = 'BMW';
            prod.Price__c = 10000;
            prod.Has_Promotion__c = TRUE;
            listOfProducts.add(prod);
        }
        insert listOfProducts;
        return listOfProducts;
    }
    public static void getNoPromoCars(Integer counter){
        List<Product2> listOfProducts = new List<Product2>();
        for (Integer i = 0; i < counter; i++) {
            Product2 prod = new Product2();
            prod.Name = 'FT-1';
            prod.Brand__c = 'BMW';
            prod.Price__c = 10000;
            //prod.Has_Promotion__c = TRUE;
            listOfProducts.add(prod);
        }
        insert listOfProducts;
        //return listOfProducts;
    }
}