DevPackage/force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Ferrari</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Lamborghini</fullName>
            </value>
            <value>
                <fullName>Mustang</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <label>Car Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevPackage/force-app/main/default/objects/Product2/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevPackage/force-app/main/default/objects/Product2/fields/Has_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Has_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Promotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/productCreationHandler.cls
public with sharing class productCreationHandler {
    @AuraEnabled
    public static String uploadFile(String product, String base64, String filename) {
        JSON2Apex productApex = parse(product);
        Id prodId = createProduct(productApex);
        System.debug('returned Id ' + prodId);
        Id values = FileUploaderClass.uploadFile1(base64, filename, prodId);
        return values;
  }
  @AuraEnabled
  public static void updateRecord(String product, String base64, String filename, String recordId) {
      JSON2Apex productApex = parse(product);
      updateProduct(productApex);
      System.debug('returned Id ' + recordId);
      if(!String.isEmpty(base64)){
        Id values = FileUploaderClass.uploadFile1(base64, filename, recordId);
      }
}
    public static JSON2Apex parse(String json) {
        return (JSON2Apex) System.JSON.deserialize(json, JSON2Apex.class);
      }

      public static Id createProduct(JSON2Apex product){
        System.debug('record' + product);
        Product2 newProduct = new Product2();
        newProduct.Name = product.model;
        newProduct.Brand__c = product.brand;
        newProduct.Color__c = product.color;
        newProduct.Price__c = product.price;
        newProduct.Has_Promotion__c = product.active;
        newProduct.Car_Type__c = 'Car';
        insert newProduct;
        return newProduct.Id;
      }
      public static void updateProduct(JSON2Apex product){
        System.debug('record' + product);
        Product2 newProduct = [SELECT Id, Brand__c, Color__c, Price__c, Name, Has_Promotion__c FROM Product2 WHERE Id = :product.id];         
        newProduct.Name = product.model;
        newProduct.Brand__c = product.brand;
        newProduct.Color__c = product.color;
        newProduct.Price__c = product.price;
        newProduct.Has_Promotion__c = product.active;
        update newProduct;
      }
    public class JSON2Apex {

        public String id;
        public String model;
        public String brand;
        public Decimal price;
        public String color;
        public Boolean active;
      
      }
}