DevPackage/force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Ferrari</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Lamborghini</fullName>
            </value>
            <value>
                <fullName>Mustang</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <label>Car Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevPackage/force-app/main/default/objects/Product2/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevPackage/force-app/main/default/objects/Product2/fields/ContentId__c.field-meta.xml
<CustomField>
    <fullName>ContentId__c</fullName>
    <label>Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DevPackage/force-app/main/default/objects/Product2/fields/Has_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Has_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Promotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tableController.cls
public with sharing class tableController {
    @AuraEnabled(cacheable=false)
    public static List<Product2> getCars(String model, String brand, String color){
        List<Product2> activeProducts = new List<Product2>();
        String modelF = '%' + model + '%';
        System.debug('entry');
        try {
            
            if(String.isEmpty(model) || String.isEmpty(brand) || String.isEmpty(color)){
                activeProducts = [SELECT Id, Brand__c, Color__c, Price__c, Name, ContentId__c, Has_Promotion__c FROM Product2 WHERE Car_Type__c = 'Car'];
            }else{
                activeProducts = [SELECT Id, Brand__c, Color__c, Price__c, Name, ContentId__c, Has_Promotion__c FROM Product2 WHERE Car_Type__c = 'Car' AND ((Brand__c =:brand) OR (Color__c =:color) OR (Name like :modelF))];
            }
            
            if(activeProducts.size() > 0) return activeProducts;

            throw new CalloutException();


        } catch (Exception e) {
            throw new AuraHandledException('There is no record that matches the entry criteria');

        }

    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getCarModel(){
        List<Product2> activeProducts = new List<Product2>();
        try {
            
                activeProducts = [SELECT Id, Price__c, Name FROM Product2 WHERE Car_Type__c = 'Car'];
            
            if(activeProducts.size() > 0) return activeProducts;

            throw new CalloutException();


        } catch (Exception e) {
            throw new AuraHandledException('There is no record that matches the entry criteria');

        }

    }

    @AuraEnabled
    public static Boolean changeStatus(String prodId){
        try {
            
                Product2 activeProducts = [SELECT Id, Price__c, Name, Has_Promotion__c FROM Product2 WHERE Id=:prodId];
                if(activeProducts.Has_Promotion__c){
                    activeProducts.Has_Promotion__c = FALSE;
                } else{
                    activeProducts.Has_Promotion__c = TRUE;

                }
                update activeProducts;
                if(activeProducts.Id != null) return activeProducts.Has_Promotion__c;

            throw new CalloutException();


        } catch (Exception e) {
            throw new AuraHandledException('Try it later.');

        }

    }
}